yml bug

diff --git a/.github/workflows/ubuntu-x86_64.yml b/.github/workflows/ubuntu-x86_64.yml
--- a/.github/workflows/ubuntu-x86_64.yml
+++ b/.github/workflows/ubuntu-x86_64.yml
@@ -24,8 +24,8 @@ jobs:
 
       - name: Fail
         run: |
-          echo "We fail when testing other builds"
-          exit 1
+          echo "Fail when testing other builds"
+          #exit 1
         shell: bash
 
       - name: Checkout code
